//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentGest.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMsg() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentGest.Properties.ResourceMsg", typeof(ResourceMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea finalizar la ejecución de la aplicación en curso?.
        /// </summary>
        internal static string MSG_ConfirmCloseApp {
            get {
                return ResourceManager.GetString("MSG_ConfirmCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar y salir de la aplicación.
        /// </summary>
        internal static string MSGToolTip_CloseApp {
            get {
                return ResourceManager.GetString("MSGToolTip_CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximizar.
        /// </summary>
        internal static string MSGToolTip_Maximize {
            get {
                return ResourceManager.GetString("MSGToolTip_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir al módulo de cine.
        /// </summary>
        internal static string MSGToolTip_MenuCine {
            get {
                return ResourceManager.GetString("MSGToolTip_MenuCine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información del sistema y configuración de la aplicación.
        /// </summary>
        internal static string MSGToolTip_MenuConfig {
            get {
                return ResourceManager.GetString("MSGToolTip_MenuConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir al módulo de libros y comics.
        /// </summary>
        internal static string MSGToolTip_MenuLibros {
            get {
                return ResourceManager.GetString("MSGToolTip_MenuLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir al módulo de música.
        /// </summary>
        internal static string MSGToolTip_MenuMusic {
            get {
                return ResourceManager.GetString("MSGToolTip_MenuMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimizar.
        /// </summary>
        internal static string MSGToolTip_Minimize {
            get {
                return ResourceManager.GetString("MSGToolTip_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurar.
        /// </summary>
        internal static string MSGToolTip_Restore {
            get {
                return ResourceManager.GetString("MSGToolTip_Restore", resourceCulture);
            }
        }
    }
}
